[2024-03-13 11:09:23,308: INFO: demo: Welcome to the log]
[2024-03-26 05:35:15,663: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-26 05:35:15,673: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-26 05:35:15,674: INFO: common: created directory at: artifacts]
[2024-03-26 05:35:15,677: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-26 05:35:15,678: INFO: 2764042521: Downloading data from https://drive.google.com/file/d/1yqXnfsFXogs21RoJvSLm63E7vEnvt5T0/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-03-26 05:35:28,284: INFO: 2764042521: Downloaded data from https://drive.google.com/file/d/1yqXnfsFXogs21RoJvSLm63E7vEnvt5T0/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-03-26 06:04:08,944: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-26 06:04:08,962: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-26 06:04:08,985: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-26 06:04:08,987: INFO: common: created directory at: artifacts]
[2024-03-26 06:04:08,989: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-26 06:04:08,990: ERROR: main: __init__() got an unexpected keyword argument 'config']
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    obj.main()
  File "e:\rohit\datascience\chest-disease-classification-from-chest-ct-scan-image\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 14, in main
    data_ingestion = DataIngestionConfig(config=data_ingestion_config)
TypeError: __init__() got an unexpected keyword argument 'config'
[2024-03-26 06:16:23,888: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-26 06:16:30,636: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-26 06:16:37,489: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-26 06:16:37,517: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-26 06:16:37,518: INFO: common: created directory at: artifacts]
[2024-03-26 06:16:44,992: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-26 06:17:21,996: ERROR: stage_01_data_ingestion: __init__() got an unexpected keyword argument 'config']
Traceback (most recent call last):
  File "e:\Rohit\DataScience\Chest-Disease-Classification-from-Chest-CT-Scan-Image\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 23, in <module>
    obj.main()
  File "e:\Rohit\DataScience\Chest-Disease-Classification-from-Chest-CT-Scan-Image\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 14, in main
    data_ingestion = DataIngestionConfig(config=data_ingestion_config)
TypeError: __init__() got an unexpected keyword argument 'config'
[2024-03-26 06:17:47,248: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-26 06:17:47,258: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-26 06:17:47,260: INFO: common: created directory at: artifacts]
[2024-03-26 06:17:54,773: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-26 06:19:54,781: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-26 06:19:54,784: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-26 06:19:54,785: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-26 06:19:54,786: INFO: common: created directory at: artifacts]
[2024-03-26 06:19:54,786: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-26 06:19:54,787: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1yqXnfsFXogs21RoJvSLm63E7vEnvt5T0/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-03-26 06:20:03,500: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1yqXnfsFXogs21RoJvSLm63E7vEnvt5T0/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-03-26 06:20:03,500: ERROR: main: 'DataIngestion' object has no attribute 'extract_zip_fie']
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    obj.main()
  File "e:\rohit\datascience\chest-disease-classification-from-chest-ct-scan-image\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.extract_zip_fie()
AttributeError: 'DataIngestion' object has no attribute 'extract_zip_fie'
[2024-03-26 06:21:50,035: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-26 06:21:50,041: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-26 06:21:50,044: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-26 06:21:50,045: INFO: common: created directory at: artifacts]
[2024-03-26 06:21:50,045: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-26 06:21:50,046: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1yqXnfsFXogs21RoJvSLm63E7vEnvt5T0/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-03-26 06:21:58,637: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1yqXnfsFXogs21RoJvSLm63E7vEnvt5T0/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-03-26 06:21:59,506: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
